export enum Actions {
  CREATE_TASK = "CREATE_TASK",
  UPDATE_TASK_NAME = "UPDATE_TASK_NAME",
  MOVE_TASK_TO_DAY = "MOVE_TASK_TO_DAY",
  MOVE_TASK_TO_BACKLOG = "MOVE_TASK_TO_BACKLOG",
  MARK_COMPLETE = "MARK_COMPLETE",
  MARK_INCOMPLETE = "MARK_INCOMPLETE",
  DELETE_TASK = "DELETE_TASK",
  UNASSIGN_TASK = "UNASSIGN_TASK",
  CREATE_BUCKET = "CREATE_BUCKET",
  DELETE_BUCKET = "DELETE_BUCKET",
}
